import "./globals.css";
import ShootingStarsAndStarsBackgroundDemo from "@/components/shooting-stars-and-stars-background-demo";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="dark"
    >
      <body className="relative min-h-screen bg-neutral-950 text-foreground antialiased">
        <div className="fixed inset-0 z-0 pointer-events-none">
          <ShootingStarsAndStarsBackgroundDemo/>
        </div>
        
        <div className="relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
